# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: WebApp
summary: Dev environment for identityProvider
description: Dev environment for identityProvider
templatePath: deploy.bicep
runner: bicep
parameters:
  - id: "workloadName"
    name: "name"
    description: "Name of the Azure Web App"
    type: "string"
    default: "identityProvider"
    readOnly: false